/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsultorRouteImport } from './routes/consultor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ConsultorIndexRouteImport } from './routes/consultor.index'
import { Route as AdminCandidatoIdRouteImport } from './routes/admin.candidato.$id'
import { Route as ConsultorCandidatoIdRouteImport } from './routes/consultor.candidato.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorRoute = ConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ConsultorIndexRoute = ConsultorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultorRoute,
} as any)
const AdminCandidatoIdRoute = AdminCandidatoIdRouteImport.update({
  id: '/candidato/$id',
  path: '/candidato/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ConsultorCandidatoIdRoute = ConsultorCandidatoIdRouteImport.update({
  id: '/candidato/$id',
  path: '/candidato/$id',
  getParentRoute: () => ConsultorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultor': typeof ConsultorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/consultor/': typeof ConsultorIndexRoute
  '/admin/candidato/$id': typeof AdminCandidatoIdRoute
  '/consultor/candidato/$id': typeof ConsultorCandidatoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/admin': typeof AdminIndexRoute
  '/consultor': typeof ConsultorIndexRoute
  '/admin/candidato/$id': typeof AdminCandidatoIdRoute
  '/consultor/candidato/$id': typeof ConsultorCandidatoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultor': typeof ConsultorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/consultor/': typeof ConsultorIndexRoute
  '/admin/candidato/$id': typeof AdminCandidatoIdRoute
  '/consultor/candidato/$id': typeof ConsultorCandidatoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consultor'
    | '/dashboard'
    | '/admin/'
    | '/consultor/'
    | '/admin/candidato/$id'
    | '/consultor/candidato/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/admin'
    | '/consultor'
    | '/admin/candidato/$id'
    | '/consultor/candidato/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consultor'
    | '/dashboard'
    | '/admin/'
    | '/consultor/'
    | '/admin/candidato/$id'
    | '/consultor/candidato/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsultorRoute: typeof ConsultorRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor': {
      id: '/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof ConsultorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/consultor/': {
      id: '/consultor/'
      path: '/'
      fullPath: '/consultor/'
      preLoaderRoute: typeof ConsultorIndexRouteImport
      parentRoute: typeof ConsultorRoute
    }
    '/admin/candidato/$id': {
      id: '/admin/candidato/$id'
      path: '/candidato/$id'
      fullPath: '/admin/candidato/$id'
      preLoaderRoute: typeof AdminCandidatoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/consultor/candidato/$id': {
      id: '/consultor/candidato/$id'
      path: '/candidato/$id'
      fullPath: '/consultor/candidato/$id'
      preLoaderRoute: typeof ConsultorCandidatoIdRouteImport
      parentRoute: typeof ConsultorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCandidatoIdRoute: typeof AdminCandidatoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCandidatoIdRoute: AdminCandidatoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ConsultorRouteChildren {
  ConsultorIndexRoute: typeof ConsultorIndexRoute
  ConsultorCandidatoIdRoute: typeof ConsultorCandidatoIdRoute
}

const ConsultorRouteChildren: ConsultorRouteChildren = {
  ConsultorIndexRoute: ConsultorIndexRoute,
  ConsultorCandidatoIdRoute: ConsultorCandidatoIdRoute,
}

const ConsultorRouteWithChildren = ConsultorRoute._addFileChildren(
  ConsultorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsultorRoute: ConsultorRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
